server:
  port: 8080
  servlet:
    context-path: /api
  ssl:
    enabled: true
    key-store: src\main\resources\keystore.p12 # 证书文件路径，相对于 classpath
    key-store-password: ygx28YGX # 生成证书时设置的密码
    key-store-type: PKCS12 # 证书类型
    key-alias: tomcat # 证书别名，生成时设置的那个
spring:
  application:
    name: weatherReport

  # MySQL?????
  datasource:
    url: jdbc:mysql://192.168.1.17:3306/Weather?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: ygx28YGX
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  # JPA??
  jpa:
    hibernate:
      ddl-auto: update  # ????/?????
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false

  wechat:
    appid: wx7e32dcfe7de20fbd
    secret: 7f1599cc42919be9098c71dc3d2d6f29
    url:
      code2session: https://api.weixin.qq.com/sns/jscode2session

# ????
logging:
  level:
    root: INFO
    com.weather: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

security:
  basic:
    enabled: false\

jwt:
    secret: biaGG8kPHIc4xphP+l0mWx4ZRL7rQQ1q9fEVRVvIewDKh1mmoT3aYTDmU2hZ7yeG
    expiration: 7200

# application.yml
qweather:
  api-host: https://nq3byg9ymh.re.qweatherapi.com # 和风天气API基地址
  host: https://nq3byg9ymh.re.qweatherapi.com
  api-key: d1ed7e9ad803465e97b344f776b4d339
  # 以下是JWT认证必需的新配置
  project-id: 49KVC33D34 # 替换为控制台获取的项目ID
  credential-id: K4WMKCG9FC # 替换为控制台获取的凭据ID
  private-key: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEIE+jEoIfQsxBirf9Ou4BAHwpIgfw0VhMWjvg+Al+vaw0
    -----END PRIVATE KEY-----
  public-key: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAhLytX+GFvcvNrizgVfNeuaugpNgHSxrV1W2F4wUbOH8=
    -----END PUBLIC KEY-----
# 可选：缓存配置
weather:
  cache:
    expire-hours: 1